# Enable verbose debug information.
verbose: false

# Your kindle address to receive e-books.
kindleAddress: test@example.com #[required]

# The cache directory.
#cacheDir: ./cache

# Enable resize image.(width x height)
# Keep image original size if not specified this value.
resizeImage: 480x360

# The maximum mobi size limit, in MBytes.
maxFileSize: 20

# SMTP Configuration that used to send e-books.
smtp: #[required]
    # domain:port,(etc. gmail.com:25)
    hostAndPort: smtp.gmail.com:465
    # Display your email address.
    # Default `account` value will used if no set this value.
    senderAddress: 
    # Use SSL to connect to the email server.
    ssl: true
    # Enable SMTP Authentication.
    account: mizzunetbackup@gmail.com
    password: 9446600459

# Specifies a kindlegen local path.
# If not specifies, use a `PATH` environment variable as default dir.
#kindlegen: kindlegen

# Proxy Configuration
#proxy: http://127.0.0.1:8888

# A list of RSS/Atom Feeds.
# each line start with `-`.
feeds:
  - http://feeds.feedburner.com/GDBcode
https://www.blog.google/rss/
  - https://hackernoon.com/tagged/deep-learning/feed
